name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liOdaEJ6FDBD5xAu"
GITHUB_OWNER = "hzwenlen"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://daohang-2ie.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://daohang-2ie.pages.dev"

